### ISSUE TITLE
Error specifying contributors

### ISSUE THREAD

**Issue by domenic** [bterlson/ecmarkup#53]
If I add

```html
<pre class="metadata">
contributors: Domenic Denicola
</pre>
```

to https://github.com/tc39/Array.prototype.includes/blob/011759c0a1385ff12f9c4f8aadb12be56afd3a30/spec.html after `<meta charset="utf-8">`, I get the error

```
$ node_modules/.bin/ecmarkup spec.html out/index.html
Error: Clauses cannot follow annexes
    at Object.next (C:\Users\Domenic\Dropbox\GitHub\tc39\Array.prototype.includes\node_modules\ecmarkup\lib\clauseNums.js:10:36)
    at Spec.getNextClauseNumber (C:\Users\Domenic\Dropbox\GitHub\tc39\Array.prototype.includes\node_modules\ecmarkup\lib\Spec.js:236:27)
    at new Clause (C:\Users\Domenic\Dropbox\GitHub\tc39\Array.prototype.includes\node_modules\ecmarkup\lib\Clause.js:36:26)
    at Spec.buildAll (C:\Users\Domenic\Dropbox\GitHub\tc39\Array.prototype.includes\node_modules\ecmarkup\lib\Spec.js:119:17)
```

It disappears if I add `copyright: false`

**Comment by bterlson** [comment]
Fixed in 1.5.2!
